name: Test Build

on:
  pull_request_review:
    types: [submitted]

jobs:
  build_release:
    runs-on: ubuntu-latest
    env:
      IJ_DOWNLOAD_URL: https://downloads.imagej.net/fiji/latest/fiji-linux64.zip
      WIKI_USER: ${{ secrets.UPDATE_USER }}
      UPDATE_PASS: ${{ secrets.UPDATE_PASS }}  # DO NOT WRITE your password here
      UPDATE_SITE: TWOMBLI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn -B package
      - name: Install ImageJ/Fiji
        run: |
          curl --silent -O ${IJ_DOWNLOAD_URL}
          unzip fiji-linux64.zip
          ./Fiji.app/ImageJ-linux64 --headless --update update
          ./Fiji.app/ImageJ-linux64 --headless --update edit-update-site ${UPDATE_SITE} https://sites.imagej.net/${UPDATE_SITE}/ "webdav:${WIKI_USER}:${UPDATE_PASS}" .
      - name: Install in ImageJ/Fiji (with Maven)
        run: mvn -B install -Dscijava.app.directory=./Fiji.app -Ddelete.other.versions=true -Dscijava.ignoreDependencies=true
